apiVersion: v1
kind: Service
metadata:
  name: coffee-svc-a
  namespace: cafe
  labels:
    app: coffee-svc-a
spec:
  ports:
  - name: coffee-svc-a
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: coffee