apiVersion: v1
kind: Service
metadata:
  name: coffee-svc-b
  namespace: cafe
  labels:
    app: coffee-svc-b
spec:
  ports:
  - name: coffee-svc-b
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: coffee