apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: vs-coffee-ab
  namespace: cafe
spec:
  virtualServerAddress: 10.192.75.121
  persistenceProfile: none
  host: cafe.example.com
  pools:
    - path: /coffee
      service: coffee-svc-a
      servicePort: 8080
      weight: 80
      extendedServiceReferences:
        - clusterName: kubeconfig-1-28
          namespace: cafe
          port: 8080
          serviceName: coffee-svc-b
          weight: 20