apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: reencrypt-mocha
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  tls:
    termination: reencrypt
    clientSSL: /Common/clientssl
    serverSSL: /Common/serverssl
    reference: bigip
  hosts:
  - mocha.example.com